[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'forge-cache'
solc_version = "0.8.10"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
